config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :products

  root 'welcome#index'
  get "about" => "welcome#about"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :image, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active?(page_name)
    "active" if params[:action] == page_name
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Beautyche</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <nav class="navbar navbar-static-top bs-docs-nav" role="banner">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
          <span class="sr-only">Toggle navigation</span>
          <i class="fa fa-navicon"></i>
        </button>
        <a class="navbar-brand" href="<%= root_path %>"><i class="fa fa-check"> Beauty Check</i></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar">
        <ul class="nav navbar-nav">
          <li class="<%= is_active?('index') %>"><%= link_to "Home", root_path %></li>
          <li class="<%= is_active?('index') %>"><%= link_to "Products", products_path %></li>
          <li class="<%= is_active?('about') %>"><%= link_to "About", about_path %></li>
          <li><a href="#">Contact</a></li>
        </ul>
      </div>
    </div><!-- /.container-fluid -->
  </nav>

  <%= yield %>



  <div class="footer">
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          <p class="text-muted ">www.beautyche.com 2014</p>
        </div>
        <div class="col-xs-6">
          <div class="text-right text-muted">
            <a href="#"><%= fa_icon "facebook 2x" %></a>
            <a href="#"><%= fa_icon "instagram 2x" %></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="bs-docs-header products-header" id="content">
  <div class="container">
    <h3><i class="fa fa-archive"></i> Products</h3>
  </div>
</div>
   <div class="row-fluid products-list">
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main products-list">
          <% @products.each do |product| %>
          <!-- PROD GRID
          ============================================================ -->

          <!-- PROD. ITEM -->
          <div class="col-md-4">
            <div class="thumbnail">
              <!-- IMAGE CONTAINER-->
              <%= image_tag(product.image.url(:square)) %>
              <!--END IMAGE CONTAINER-->
              <!-- CAPTION -->
              <div class="caption">
                <h4 class=""><%= product.name %></h4>
                <p class="text-muted"><%= product.description %></p>

                <div class="row">
                  <div class="col-md-6">
                    <p class="lead"><%= product.price %></p>
                  </div>
                  <div class="col-md-6">
                    <a class="btn btn-success btn-block" href="#">Add to cart</a>
                  </div>
                </div>
              </div>
              <!--END CAPTION -->
            </div>
            <!-- END: THUMBNAIL -->
          </div>
          <!-- PROD. ITEM -->
          <% end %>
        </div>

</div>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Image:</strong>
  <%= @product.image %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/welcome/about.html.erb
<div class="bs-docs-header" id="content">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag "about.jpg", height: '140', width: '140', class: "img-che img-circle img-responsive center-block"%>
      </div>
      <div class="col-md-8">
        <h2>Che Salamat-Novilla <small>PROPRIETOR</small></h2>
        <small><em>"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor"</em></small>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="bs-docs-header" id="content">
  <div class="container">
    <%= image_tag "logo.svg", class: "img-responsive"%>
    <br>
    <p>Welcome! Feel free to browse our products.</p>
    <br>
    <p><a href="<%= products_path %>" class="btn btn-info btn-lg" role="button">View products</a></p>
  </div>
</div>